apiVersion: policy.openservicemesh.io/v1alpha1
kind: IngressBackend
metadata:
  name: sample1-ingressbackend
  namespace: sample1
spec:
  backends:
  - name: aks-helloworld-svc
    port:
      number: 80
      protocol: https
    tls:
      skipClientCertValidation: false
  sources:
  - kind: AuthenticatedPrincipal
    name: nginx.app-routing-system.cluster.local
