apiVersion: policy.openservicemesh.io/v1alpha1
# use this definition when using add-on for both osm and web application routing together
# this has kind: Service in sources section for added protection
kind: IngressBackend
metadata:
  name: sample1-ingressbackend
  namespace: sample1
spec:
  backends:
  - name: aks-helloworld-svc
    port:
      number: 80
      protocol: https
    tls:
      skipClientCertValidation: false
  sources:
  - kind: Service
    name: nginx
    namespace: app-routing-system
  - kind: AuthenticatedPrincipal
    name: nginx.app-routing-system.cluster.local
